### PR TITLE
Bugfix: last floor was not created, handling bad input

### PR DESCRIPTION
**Pull request by ArthurAtangana**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] ✅ Test
- [ ] 🧑‍💻 Refactor

## Description

when creating the floors, we had a discrepancy in the for loop that didn't account for indexing at 0 and having x number of floors. we would end up with one less, and the elevator would never unload or load passengers on that floor.

Also, the parser is now not passing bad inputs to the destination dispatcher. This means that if there is an input from the top floor that wants to go up, or an input from the bottom floor going down, it will not even show in the system and be ignored instantly

## How to test

run the scenario 7 and 8 recently added and see if there is a load/unload on the top floor.

run scenario 9 and 10 and see if the first inputs are skipped.

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why:
- [ ] I need help with writing tests:.

## Screenshots

### CODE REVIEW

**Comment by VictoriaMalouf** [comment]
Added logic to:
- prevent the floor from sending passengers whose destination floor is out of range
- prevent the elevator from moving out of range

Before (scenario 9):
Screen Shot 2024-03-28 at 9 21 55 PM

After (scenario 9):
Screen Shot 2024-03-28 at 9 19 50 PM

Before (scenario 10):
Screen Shot 2024-03-28 at 9 23 09 PM

After (scenario 10):
Screen Shot 2024-03-28 at 9 24 38 PM

**Review by mpdesantis — DISMISSED** [review]
Champions both! Ran through the scenarios, looks good to me. Thanks for this! Nice debugging. You are debest.

**Comment by ArthurAtangana** [comment]
feel like the elevator shouldnt even start if the input is invalid.

**Comment by VictoriaMalouf** [comment]
> feel like the elevator shouldnt even start if the input is invalid.

The elevator can only know if an input is invalid by checking the destinationFloor in `load(MovePassengersCommand command)`.

However, if the elevator is requested on a valid floor, it won't know the passengers intentions until it picks them up. 

In scenario 9 it doesn't move because it is already on the source floor but for scenario 10 it has to travel to floor 7.

Maybe scheduler logic would be required here?

**Comment by ArthurAtangana** [comment]
Added parser checks for bad inputs. There is a case where if we have only 1 input and it is bad, the destination dispatcher fails but this should probably never happen.

**Review by mpdesantis — APPROVED** [review]
Looks good. Thanks for the changes. 
These dang hardware people installing down buttons on bottom floors and up buttons on top floors I tell ya..

**Review by VictoriaMalouf — APPROVED** [review]

**Pull request merged**
